Topo Analysis
========================================================

```{r, message=FALSE,warning=FALSE}
#----  Load libraries
library(ggplot2)
library(plyr)
library(caret)
library(doMC)
library(yaml)
library(xtable)
library(reshape2)
library(MASS)
library(grid)
library(gridExtra)
library(hash)
library(devtools)
library(knitr)
library(glmnet)
library(RMySQL)
library(DBI)

load_all("~/work/code/Rpackages/cytominr")

registerDoMC()
#registerDoSEQ()
```

```{r, eval=FALSE}
rm(list=ls())

con <- dbConnect(MySQL(),user="cpuser", password="cPus3r",
                 dbname="2012_08_20_TopoChipScreening_deBoerLab", host="imgdb02")

rs <- dbSendQuery(con, 'select I.Image_Metadata_ArrayNumber as Array, avg(ALPCytoplasm_Intensity_IntegratedIntensity_ALP4Corr) as meanALP, median(ALPCytoplasm_Intensity_IntegratedIntensity_ALP4Corr) as medALP, stddev(ALPCytoplasm_Intensity_IntegratedIntensity_ALP4Corr) as stdALP, count(*) as ncells from TiALP_Per_Image as I, TiALP_Per_Object as O where I.ImageNumber = O.ImageNumber group by I.Image_Metadata_ArrayNumber')
tbl <- fetch(rs)
print(xtable(tbl), file="summary_alp_per_cell.tex", size="tiny")

rs <- dbSendQuery(con, 'select Image_Metadata_ArrayNumber as Array, count(*) as nimages, sum(Image_Count_Cells) as ncells, sum(Image_Count_Cells) /count(*) as ncells_per_image from TiALP_Per_Image group by Image_Metadata_ArrayNumber')
tbl <- fetch(rs)
print(xtable(tbl), file="summary_alp_per_image.tex", size="tiny")

dbDisconnect(con)


```

```{r, Load_and_fix_data, eval=FALSE}
rm(list=ls())
cf = '../input/TIALP-B1/well-summary-profile_mean-median-none-none.yml'
B <- profile.data(cf)
Xmorp <- feats(B)
Xtopo <- factors(B)
names(Xtopo) <- sub('TiALP_Per_Image.Image_Metadata_', '', names(Xtopo))
names(Xtopo) <- sub('Image_Metadata_', '', names(Xtopo))

# Fix meta data issue # HACK!!
meta_csv <- read.csv('../input/Metadatafile TopoChip_TiALP_array1_allunits_pruned_fixedmetaproblem.csv')
fname_f <- data.frame(FileName_Actin_w_array_name = Xtopo$FileName_Actin_w_array_name)
meta_csv_joined <- join(fname_f, meta_csv, type="left")
names(meta_csv_joined) <- sub('Metadata_', '', names(meta_csv_joined))
Xtopo <- meta_csv_joined
saveRDS(Xtopo, file='Xtopo.rda')
saveRDS(Xmorp, file='Xmorp.rda')
rm(list=c("meta_csv_joined", "meta_csv"))
```

```{r Aggregate_across_replicates, eval=FALSE}
Xmorp0 <- Xmorp
Xmorp0$featureidx <- Xtopo$featureidx
Xmorp0 <- ddply(Xmorp0, .(featureidx), numcolwise(median))
featureidx <- Xmorp0$featureidx
Xmorp0 <- Xmorp0[,!(names(Xmorp0) %in% c('featureidx'))]
saveRDS(Xmorp0, file='Xmorp0.rda')
saveRDS(featureidx, file='featureIdx.rda')

```

```{r pick_featureidxs_for_classification, eval=FALSE}

Xmorp <- readRDS('../results/alp_prediction/19e48bfd/Xmorp.rda')
Xtopo <- readRDS('../results/alp_prediction/19e48bfd/Xtopo.rda')

pred_var <- "ALPCytoplasm_Intensity_IntegratedIntensity_ALP4Corr"

Xalp0 <- data.frame(featureidx=Xtopo$featureidx, 
                    alp = Xmorp[,pred_var], 
                    fname=Xtopo$FileName_Actin_w_array_name)
Xalp1 <- ddply(Xalp0, .(featureidx), summarize, mean = mean(alp), sd = sd(alp), n = length(alp), snr = mean(alp)/sd(alp), 
              featureidx=featureidx[1])

g1_low  <- Xalp1$featureidx[((Xalp1$sd*2)<Xalp1$mean) & (Xalp1$mean < 250)]
g1_high <- Xalp1$featureidx[((Xalp1$sd*2)<Xalp1$mean) & (Xalp1$mean > 450)]

u_low  <- (Xalp0$featureidx %in% g1_low)  & (Xalp0$alp < 200)
u_high <- (Xalp0$featureidx %in% g1_high) & (Xalp0$alp > 530)

fn_low  <- as.character(Xtopo$FileName_Actin_w_array_name[u_low])
fn_high <- as.character(Xtopo$FileName_Actin_w_array_name[u_high])

d_low  <- Xmorp[u_low,]
d_high <- Xmorp[u_high,]

y_low  <- rep('l', sum(u_low))
y_high <- rep('h', sum(u_high))

D <- rbind(d_low, d_high)
y <- factor(c(y_low, y_high))
fn <- c(fn_low, fn_high)

D <- D[,-nearZeroVar(D)]
exclude_cols <- unique(c(names(D)[grep('ALP', names(D))], pred_var))
D <- as.matrix(D[, !(names(D) %in% exclude_cols)])

set.seed(1)
n <- length(y)
v <- sample(n)
pctr <- 0.5
ntr <- ceiling(pctr * n)
tr_vec <- v[1:ntr]
te_vec <- v[(1 + ntr):n]

Dtr  <- D[tr_vec, ]
ytr  <- y[tr_vec]
fntr <- fn[tr_vec]

Dte  <- D[te_vec, ]
yte  <- y[te_vec]
fnte <- fn[te_vec]

method = 'rf'
registerDoMC() 
#registerDoSEQ() 
#fit_ <- train(matrix(rnorm(1000), nrow=100, ncol=10), rnorm(100), method=method)
fit <- train(Dtr, ytr, method = method, tuneLength = 5, 
             preProc = c("center", "scale"), 
             trControl = trainControl(method = "repeatedcv", number = 5, repeats = 1))

print(fit)
y_out <- predict(fit, Dte)
table(y_out, yte)

write.csv(cbind(fnte, as.character(yte), as.character(y_out)), 'labels.csv')
library(randomForest)
varImpPlot(randomForest(D, y), n.var=10)

```

```{r univariate, eval=FALSE}
# Perform t-test to identify variables in which differences are the most 
df <- data.frame()
D <- as.data.frame(D)
for (feat in names(D)) {
  x <- D[,feat]
  xl <- x[y=="l"]
  xh <- x[y=="h"]
  df0 <- data.frame(name=feat, 
                    lowAlP_mean=mean(xl), highALP_mean=mean(xh), 
                    lowAlP_sd=sd(xl), highALP_sd=sd(xh), 
                    pval=t.test(xl,xh)$p.value)
  if (NROW(df) == 0) df <- df0 else df <- rbind(df, df0)  
}
write.csv(df[with(df, order(pval)),], 'ttest.csv', row.names = F)



```

```{r cleanup_X, eval=FALSE}
Xmorp0 <- readRDS('../results/alp_prediction/e052f898/Xmorp0.rda')
featureIdx <- readRDS('../results/alp_prediction/e052f898/featureIdx.rda')
Xmorp0 <- Xmorp0[,-nearZeroVar(Xmorp0)]
Xmorp0 <- Xmorp0[,-findCorrelation(cor(Xmorp0))]

```

```{r test_correlations, eval=FALSE}

# Inspect correlations between groups of variables 
rm(list=ls())
Xmorp0 <- readRDS('../results/alp_prediction/018ce9ee/Xmorp0.rda')

categ <- function(v) {
  v <- as.character(v)
  comp <- simplify2array(strsplit(v,"_")[[1]][1])
  type <- simplify2array(strsplit(v,"_")[[1]][2])
  if (type=='RadialDistribution') type <- 'RadDir'
  if (type=='Correlation') type <- 'Corr'
  if (type=='Granularity') type <- 'Gran'
  clist <- c('ALP4Corr', 'Actin4Corr', 'DNA4Corr')
  channel <- clist[unlist(lapply(clist, function(t) length(grep(t, v)) != 0))]
  if (length(channel)!=1) channel <- "None"
  data.frame(feature=v,comp,type,channel)
}

x <- Xmorp0
x <- x[,-nearZeroVar(x)]
x <- as.matrix(x)
x <- cor(x)
x <- as.array(x)
x[upper.tri(x,diag=T)] <- 0
x <- melt(x)
x <- x[abs(x$value) > 0.9,]
x <- x[x$value != 1,]
categs <- ldply(names(Xmorp0), categ)
c1 <- c2<- categs
names(c1) <- paste("f1", names(c1), sep="_")
names(c2) <- paste("f2", names(c2), sep="_")
xm <- x
xm <-  merge(c1, xm, by.x="f1_feature", by.y="X1")
xm <-  merge(c2, xm, by.x="f2_feature", by.y="X2")
xm0 <- merge(c1,c2, all=T)

table(xm$f1_comp,xm$f2_comp)

```

```{r prepare_data, eval=FALSE}
pred_var <- c("ALPCytoplasm_Intensity_IntegratedIntensity_ALP4Corr")
exclude_cols <- unique(c(names(Xmorp0)[grep('ALP', names(Xmorp0))],
                         #names(Xmorp0)[grep('Intensity', names(Xmorp0))],
                         pred_var))
y <- Xmorp0[, pred_var]
Xmorp0m <- as.matrix(Xmorp0[, !(names(Xmorp0) %in% exclude_cols)])

```

```{r test_lm, eval=FALSE}

Xms <- scale(Xmorp0m)
m <- lm(y ~ Xms)
coefs <- summary(m)$coefficients
coefs <- coefs[2:NROW(coefs),]
print(xtable(coefs[coefs[,4] < 0.0005,]), file="top_feats_lm.tex", size="tiny")

C1 <- data.frame(t=coefs[,3])
row.names(C1) <- gsub('Xms', '', row.names(coefs))
C2 <- abs(cor(Xms, y))
C3 <- merge(C1, C2, by=0, all=TRUE)
qplot(t, V1, data=C3) + ylab('Abs Correlation Coef.') + xlab('t-value in regression')
ggsave('regression_correlation.pdf')
 
C4 <- abs(C2)
C4 <- as.data.frame(C4[order(C4,decreasing=T),])
names(C4) <- c("Correlation")
head(C4)
print(xtable(subset(C4, Correlation > .35)), file="top_feats_corr.tex", size="tiny")

```

```{r predict_ALP, eval=FALSE}
method = "lm"
#method = "pls"
#method = "lm"
n <- length(y)
v <- sample(n)
pctr <- 0.5
ntr <- ceiling(pctr * n)
tr_vec <- v[1:ntr]
te_vec <- v[(1 + ntr):n]

Xtr <- Xmorp0m[tr_vec, ]
ytr <- y[tr_vec]
Xte <- Xmorp0m[te_vec, ]
yte <- y[te_vec]


registerDoMC() 
#registerDoSEQ() 
#fit_ <- train(matrix(rnorm(1000), nrow=100, ncol=10), rnorm(100), method=method)
fit <- train(Xtr, ytr, method = method, tuneLength = 15, 
             preProc = c("center", "scale"), 
             trControl = trainControl(method = "repeatedcv", number = 5, repeats = 1))


y_out <- predict(fit, Xte)
plot(yte, y_out)
cor(yte, y_out)

coefs <- abs(fit$finalModel$coefficients)
coefs <- sort(coefs[!(names(coefs) %in% c("(Intercept)"))], decreasing=T)
coefs <- coefs[1:21]
coefs_lab <- factor(1:length(coefs), labels=names(coefs))
qplot(coefs_lab,coefs, geom='bar', stat='identity') + coord_flip() + xlab('Features') + ylab('Regression Coef')

```

```{r boxcox}
rm(list=ls())
library(car)
D <- readRDS('../results/alp_prediction/19e48bfd/Xmorp.rda')
# HACK to remove some outliers. This should be visually verified!
D <- D[D$Cells_AreaShape_Area < quantile(D$Cells_AreaShape_Area, 0.98)[[1]], ] 
D <- D[,-nearZeroVar(D)]
D <- D[,-grep("EulerNumber", names(D))] # HACK! Removed because bc doesn't work with it
bcp <- function(v) {m = min(v)-1; bcPower(v-m, powerTransform(v-m)$lambda)}
Dbx <- colwise(bcp)(D)
saveRDS(Dbx, file='Dbx.rda')
```

```{r, eval=FALSE}

library(colorRamps)
library(RColorBrewer)

Xtopo <- readRDS('../results/alp_prediction/19e48bfd/Xtopo.rda')
pred_var <- "ALPCytoplasm_Intensity_IntegratedIntensity_ALP4Corr"

D <- readRDS('../results/HEAD/2558a576/Dbx.rda')

# compute correlation
corD <- cor(D)

# get the correlation of features wrt the pred_var, and use it to rank features
vmean <- corD[,pred_var]

# Remove ALP features
flag <- !(seq(length(vmean)) %in% grep("^ALPCytoplasm_", names(vmean)))
corD <- corD[flag,flag]
vmean <- vmean[flag] 

# Remove features that are obviously correlation with Nuclei_Number_Object_Number
# This is a bit of a hack because it was done after the analysis, but it 
# doesn't affect the result in any way, only makes the viz cleaner
flag <- !(names(vmean) %in% c('Cells_Number_Object_Number', 'Cells_Parent_Nuclei', 
                              'Cells_Neighbors_FirstClosestObjectNumber_Expanded',
                              'Cells_Neighbors_SecondClosestObjectNumber_Expanded',
                              'Cells_Neighbors_FirstClosestDistance_Expanded'))
corD <- corD[flag,flag]
vmean <- vmean[flag] 

# Threshold based on correlation wrt the pred_var
cor_thresh <- 0.3
flag <- abs(vmean) > cor_thresh
corD <- corD[flag,flag]
vmean <- vmean[flag] 

# Threshold based on correlation wrt the pred_var
flag <- !(seq(length(vmean)) %in% findCorrelation(corD, cutoff=0.90))
corD <- corD[flag,flag]
vmean <- vmean[flag] 




# Build dendrogram based on correlation between features
tree <- hclust(as.dist(1 - abs(corD)))

# Label the nodes
tree.labels <- tree$labels
tree$labels <- unlist(lapply(tree$labels, function(x) sprintf("%0.2f:%s", vmean[[as.character(x)]], as.character(x))))

# color the nodes
NCOLORS <- 10
leafcols_pos <- colorRampPalette(brewer.pal(9, "Greens"))(NCOLORS)
leafcols_neg <- colorRampPalette(brewer.pal(9, "Reds"))(NCOLORS)

get_leafcol <- function(x, s) if (s < 0) leafcols_neg[[x]] else leafcols_pos[[x]]

rescale_col <- function(x) 4 + ceiling((NCOLORS-4) * (abs(x)-min(abs(vmean))) / (max(abs(vmean)-min(abs(vmean)))))

lab.col <- lapply(tree.labels, function(x) get_leafcol(rescale_col(vmean[[as.character(x)]]), sign(vmean[[as.character(x)]])))
names(lab.col) <- tree$labels
dendro <- as.dendrogram(tree)

colLab <- function(n) {
    if (is.leaf(n))
        attr(n, "nodePar") <- c(attr(n, "nodePar"), list(lab.col = lab.col[[attr(n, "label")]]))
    n
}

dendroC <- dendrapply(dendro, colLab)

# plot dendrogram
pdf(width = 8, height = 5)
par(mar = c(0, 0, 0, 25))
plot(dendroC, horiz = TRUE, type = "triangle", center = T)
dev.off()
```

```{r, eval=FALSE}

library(sem)
library(corrgram)

shorten_names <- function(df) { 
names(df)[names(df)=="Cells_AreaShape_Area"] <- "lArea"
names(df)[names(df)=="Cells_AreaShape_MajorAxisLength"] <- "MajorAx"                
names(df)[names(df)=="Cells_AreaShape_MinorAxisLength"] <- "MinorAx"               
names(df)[names(df)=="Cells_AreaShape_Solidity"] <- "Solidity"    
names(df)[names(df)=="Cells_Intensity_IntegratedIntensity_Actin4Corr"] <- "IntegIntActin"
names(df)[names(df)=="Cells_Intensity_MaxIntensity_Actin4Corr"] <-  "MaxIntActin"  
names(df)[names(df)=="Cells_Intensity_StdIntensity_Actin4Corr"] <-  "StdIntActin"        
names(df)[names(df)=="Cells_Neighbors_PercentTouching_Expanded"] <- "PCtouch"
names(df)[names(df)=="Nuclei_Number_Object_Number"] <- "Count" # Not exactly cell count
names(df)[names(df)=="Cells_AreaShape_Zernike_2_0"] <- "Zer2_0"
names(df)[names(df)=="Cells_AreaShape_Extent"] <- "Extent"
names(df)[names(df)=="Cells_AreaShape_Perimeter"] <- "Peri"
names(df)[names(df)=="Cells_Intensity_MassDisplacement_Actin4Corr"] <- "MassDispActin"
names(df)[names(df)=="Cells_Neighbors_SecondClosestDistance_Expanded"] <- "Neigbor2ndDist"
names(df)[names(df)=="Cells_RadialDistribution_FracAtD_Actin4Corr_1of4"] <- "RadDirActin"
df
}


map_to_log <- function(df) { 
df[,"Cells_AreaShape_Area"] <- log(df[,"Cells_AreaShape_Area"])
df[,"Cells_AreaShape_MajorAxisLength"] <- log(df[,"Cells_AreaShape_MajorAxisLength"])               
df[,"Cells_AreaShape_MinorAxisLength"] <- log(df[,"Cells_AreaShape_MinorAxisLength"])      
df[,"Cells_AreaShape_Solidity"] <- log(df[,"Cells_AreaShape_Solidity"]) 
df[,"Cells_Intensity_IntegratedIntensity_Actin4Corr"] <- log(df[,"Cells_Intensity_IntegratedIntensity_Actin4Corr"]) 
df[,"Cells_Intensity_MaxIntensity_Actin4Corr"] <- log(df[,"Cells_Intensity_MaxIntensity_Actin4Corr"]) 
df[,"Cells_Intensity_StdIntensity_Actin4Corr"] <- log(df[,"Cells_Intensity_StdIntensity_Actin4Corr"])      
df[,"Cells_Neighbors_PercentTouching_Expanded"] 
df[,"Nuclei_Number_Object_Number"] 
df
}


Dsub <- subset(D[,names(vmean)], Cells_AreaShape_Area < 150000 )
#Dsub_log <- map_to_log(as.data.frame(Dsub))
Dsub_r <- shorten_names(as.data.frame(Dsub))
Dsub_m <- as.matrix(Dsub)
Dsub_mr <- as.data.frame(Dsub_m)
names(Dsub_mr) <- names(Dsub_r)
hexplom(Dsub_mr, xbins=80)



Dsub.cov <- cov(Dsub)
model.Dsub <- specifyModel('model1.txt') 
Dsub.sem <- sem(model.Dsub, Dsub.cov, nrow(Dsub))
summary(Dsub.sem)
fs <- fscores(Dsub.sem)
Dsub_f <- Dsub_m %*% fs

hexplom(Dsub_f, xbins=80)

D3 <- subset(D, Nuclei_Number_Object_Number < 2)
DD3 <- D3[,c("Nuclei_Number_Object_Number", "Cells_AreaShape_Area")]

corrgram(DD3, order=TRUE, lower.panel=panel.ellipse,
  upper.panel=panel.pts, text.panel=panel.txt,
  diag.panel=panel.minmax)


#pathDiagram(Dsub.sem, 'graph', min.rank=NULL, max.rank=NULL, same.rank=NULL, variables=Dsub.sem$var.names, ignore.double=TRUE, edge.labels=c("names", "values", "both"), size=c(8, 8),   rank.direction=c("LR", "TB"), digits=2, standardize=FALSE, output.type=c("graphics", "dot"), graphics.fmt="pdf", dot.options=NULL)



```